package com.decentralchain.transaction.smart.script.estimator

import com.decentralchain.lang.v1.estimator.ScriptEstimatorV1

class ContractScriptComplexityV1Test extends ContractScriptComplexityTest(ScriptEstimatorV1)