package com.decentralchain.transaction.smart.script.estimator

import com.decentralchain.lang.v1.estimator.v2.ScriptEstimatorV2

class ContractScriptComplexityV2Test extends ContractScriptComplexityTest(ScriptEstimatorV2)